### ISSUE TITLE
not so friendly Ն

### ISSUE THREAD

**Issue by antranigv** [wiktor-b/leggie#3]
it looks like that capital letter "Now" and capital letter "Liwn" are similar.
"Now" is http://unicode-table.com/en/0546/ and "Liwn" is http://unicode-table.com/en/053C/

attached a screenshot at well.

the first letter is Ն and the second is Լ, under them are their small letter cases.

in the terminal under it, is the same using the Monospace font.

![2016-07-11_21 56 55](https://cloud.githubusercontent.com/assets/5600749/16741242/7d9ff4e2-47b3-11e6-871d-0e202dacb693.png)

**Comment by wikkyk** [comment]
Check out commit f7e0a9c53ee2202c22df593ad8ba86222ba57b1a - I've updated capital Now to be a bit more rounded.

**Comment by antranigv** [comment]
the new "New" (Նու) is ideal! :+1: :)

![2016-07-15_00 07 06](https://cloud.githubusercontent.com/assets/5600749/16854043/5243d7cc-4a20-11e6-873f-c2f081a543c1.png)
